version: '3.4'

networks:
  demowebapiapp:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=sa@123456
    networks:
        - demowebapiapp
  dotnetapi.dockerwithmssql:
    container_name: demowebapi
    image: ${DOCKER_REGISTRY-}dotnetapidockerwithmssql
    build:
      context: .
      dockerfile: DotNetAPI.DockerWithMSSQL/Dockerfile
    ports:
        - 8001:80
    depends_on:
        - demoappdb
    environment:
        - DB_HOST=demoappdb
        - DB_NAME=EmpDB
        - DB_SA_PASSWORD=sa@123456
    networks:
        - demowebapiapp